CREATE SCHEMA IF NOT EXISTS crimedb;
SET search_path TO crimedb;

CREATE TABLE Address (
    address_id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    street_address  VARCHAR(255),
    city            VARCHAR(100),
    state           VARCHAR(100),
    postal_code     VARCHAR(20),
    country         VARCHAR(100)
);

CREATE TABLE Person (
    personID        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gender          VARCHAR(1) CHECK (gender IN ('M', 'F', 'O', 'U')),
    birth_date      DATE,
    first_name      VARCHAR(100),
    middle_name     VARCHAR(100),
    last_name       VARCHAR(100),
    address_id      INT,
    occupation      VARCHAR(100),
    contact_number  VARCHAR(15),
    FOREIGN KEY (address_id) REFERENCES Address(address_id) ON DELETE SET NULL
);

CREATE TABLE Case_Details (
    case_id         INT GENERATED BY DEFAULT AS IDENTITY,
    open_date       DATE NOT NULL,
    crime_date      DATE,
    end_date        DATE,
    complaint_detail VARCHAR(255),
    crime_type      VARCHAR(50),
    crime_location  INT,
    case_status     VARCHAR(10) CHECK (case_status IN ('open', 'closed', 'on_hold')),
    personID        INT,
    PRIMARY KEY (case_id, open_date),
    FOREIGN KEY (personID) REFERENCES Person(personID) ON DELETE SET NULL,
    FOREIGN KEY (crime_location) REFERENCES Address(address_id) ON DELETE SET NULL
);

CREATE TABLE Trial (
    case_id         INT NOT NULL,
    open_date       DATE NOT NULL,
    trial_number    INT NOT NULL,
    hearing         DATE,
    judge_id        INT,
    court_level     VARCHAR(50),
    PRIMARY KEY (case_id, open_date, trial_number),
    FOREIGN KEY (case_id, open_date) REFERENCES Case_Details(case_id, open_date) ON DELETE CASCADE,
    FOREIGN KEY (judge_id) REFERENCES Person(personID) ON DELETE SET NULL
);

CREATE TABLE Police_Officer (
    p_personID      INT PRIMARY KEY,
    rank            VARCHAR(50),
    department      VARCHAR(100),
    FOREIGN KEY (p_personID) REFERENCES Person(personID) ON DELETE CASCADE
);

CREATE TABLE Criminal (
    c_personID      INT PRIMARY KEY,
    c_family_contact VARCHAR(15),
    FOREIGN KEY (c_personID) REFERENCES Person(personID) ON DELETE CASCADE
);

CREATE TABLE Suspect (
    s_personID          INT PRIMARY KEY,
    physical_description VARCHAR(255),
    family_contact      VARCHAR(15),
    arrest_status       VARCHAR(50) CHECK (arrest_status IN ('wanted', 'arrested', 'released')),
    FOREIGN KEY (s_personID) REFERENCES Person(personID) ON DELETE CASCADE
);

CREATE TABLE Victim (
    v_personID      INT PRIMARY KEY,
    harm_details    VARCHAR(255),
    family_contact  VARCHAR(15),
    FOREIGN KEY (v_personID) REFERENCES Person(personID) ON DELETE CASCADE
);

CREATE TABLE Witness (
    w_personID      INT PRIMARY KEY,
    family_contact  VARCHAR(15),
    testimony       VARCHAR(255),
    FOREIGN KEY (w_personID) REFERENCES Person(personID) ON DELETE CASCADE
);

CREATE TABLE Evidence (
    evidence_id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description       VARCHAR(255),
    collection_date   DATE,
    location_id       INT,
    file_key          VARCHAR(1024),
    file_content_type VARCHAR(255),
    file_size         INTEGER,
    FOREIGN KEY (location_id) REFERENCES Address(address_id) ON DELETE SET NULL
);

CREATE TABLE Collected_For (
    evidence_id     INT NOT NULL,
    case_id         INT NOT NULL,
    open_date       DATE NOT NULL,
    PRIMARY KEY (evidence_id, case_id, open_date),
    FOREIGN KEY (evidence_id) REFERENCES Evidence(evidence_id) ON DELETE CASCADE,
    FOREIGN KEY (case_id, open_date) REFERENCES Case_Details(case_id, open_date) ON DELETE CASCADE
);

CREATE TABLE Testifies_In (
    case_id         INT NOT NULL,
    open_date       DATE NOT NULL,
    w_personID      INT NOT NULL,
    testimony       VARCHAR(255),
    PRIMARY KEY (case_id, open_date, w_personID),
    FOREIGN KEY (case_id, open_date) REFERENCES Case_Details(case_id, open_date) ON DELETE CASCADE,
    FOREIGN KEY (w_personID) REFERENCES Witness(w_personID) ON DELETE CASCADE
);

CREATE TABLE Assigned_To (
    p_personID      INT NOT NULL,
    case_id         INT NOT NULL,
    open_date       DATE NOT NULL,
    PRIMARY KEY (p_personID, case_id, open_date),
    FOREIGN KEY (p_personID) REFERENCES Police_Officer(p_personID) ON DELETE CASCADE,
    FOREIGN KEY (case_id, open_date) REFERENCES Case_Details(case_id, open_date) ON DELETE CASCADE
);

CREATE TABLE Affected_By (
    v_personID      INT NOT NULL,
    case_id         INT NOT NULL,
    open_date       DATE NOT NULL,
    PRIMARY KEY (v_personID, case_id, open_date),
    FOREIGN KEY (v_personID) REFERENCES Victim(v_personID) ON DELETE CASCADE,
    FOREIGN KEY (case_id, open_date) REFERENCES Case_Details(case_id, open_date) ON DELETE CASCADE
);

CREATE TABLE Punishment (
    c_personID      INT NOT NULL,
    case_id         INT NOT NULL,
    open_date       DATE NOT NULL,
    fine            INT,
    jail_start_date DATE,
    jail_end_date   DATE,
    death_penalty   VARCHAR(1) CHECK (death_penalty IN ('Y', 'N')),
    PRIMARY KEY (c_personID, case_id, open_date),
    FOREIGN KEY (c_personID) REFERENCES Criminal(c_personID) ON DELETE CASCADE,
    FOREIGN KEY (case_id, open_date) REFERENCES Case_Details(case_id, open_date) ON DELETE CASCADE
);

CREATE TABLE Involved_In (
    case_id         INT NOT NULL,
    open_date       DATE NOT NULL,
    s_personID      INT NOT NULL,
    PRIMARY KEY (case_id, open_date, s_personID),
    FOREIGN KEY (case_id, open_date) REFERENCES Case_Details(case_id, open_date) ON DELETE CASCADE,
    FOREIGN KEY (s_personID) REFERENCES Suspect(s_personID) ON DELETE CASCADE
);

CREATE TABLE Linked_to (
    case_id         INT NOT NULL,
    open_date       DATE NOT NULL,
    s_personID      INT NOT NULL,
    evidence_id     INT NOT NULL,
    PRIMARY KEY (case_id, open_date, s_personID, evidence_id),
    FOREIGN KEY (case_id, open_date, evidence_id) REFERENCES Collected_For(case_id, open_date, evidence_id) ON DELETE CASCADE,
    FOREIGN KEY (s_personID) REFERENCES Suspect(s_personID) ON DELETE CASCADE
);

CREATE TABLE Pointed_to (
    case_id         INT NOT NULL,
    open_date       DATE NOT NULL,
    s_personID      INT NOT NULL,
    w_personID      INT NOT NULL,
    PRIMARY KEY (case_id, open_date, s_personID, w_personID),
    FOREIGN KEY (case_id, open_date, w_personID) REFERENCES Testifies_In(case_id, open_date, w_personID) ON DELETE CASCADE,
    FOREIGN KEY (s_personID) REFERENCES Suspect(s_personID) ON DELETE CASCADE
);

CREATE TABLE App_User (
    user_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(100) UNIQUE NOT NULL,
    email           VARCHAR(255) UNIQUE NOT NULL,
    hashed_password TEXT NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_login      TIMESTAMPTZ,
    mobile_number   VARCHAR(15)
);

CREATE INDEX idx_person_address_id ON Person(address_id);
CREATE INDEX idx_case_details_crime_location ON Case_Details(crime_location);
CREATE INDEX idx_case_details_open_date ON Case_Details(open_date);
CREATE INDEX idx_case_details_case_status ON Case_Details(case_status);
CREATE INDEX idx_case_details_personid ON Case_Details(personID);
CREATE INDEX idx_address_city ON Address(city);
CREATE INDEX idx_evidence_location_id ON Evidence(location_id);
CREATE INDEX idx_trial_judge_id ON Trial(judge_id);
CREATE INDEX idx_collected_for_case ON Collected_For(case_id, open_date);
CREATE INDEX idx_testifies_in_w_personid ON Testifies_In(w_personID);
CREATE INDEX idx_assigned_to_case ON Assigned_To(case_id, open_date);
CREATE INDEX idx_affected_by_case ON Affected_By(case_id, open_date);
CREATE INDEX idx_punishment_case ON Punishment(case_id, open_date);
CREATE INDEX idx_involved_in_s_personid ON Involved_In(s_personID);
CREATE INDEX idx_linked_to_s_personid ON Linked_to(s_personID);
CREATE INDEX idx_linked_to_evidence_id ON Linked_to(evidence_id);
CREATE INDEX idx_pointed_to_s_personid ON Pointed_to(s_personID);
CREATE INDEX idx_pointed_to_w_personid ON Pointed_to(w_personID);
